import time
print("|------------------------|")
print("|                        |")
print("|        download        |")
print("|       cnt.website      |")
print("|           ...          |")
print("|                        |")
print("|                        |")
print("|________ver1.0.0________|")
time.sleep(3)
print("|------------------------|")
print("|                        |")
print("|        download        |")
print("|      web.expansion     |")
print("|           ...          |")
print("|                        |")
print("|                        |")
print("|________ver1.0.0________|")
time.sleep(3)
print("|------------------------|")
print("|                        |")
print("|        download        |")
print("|        complet!!       |")
print("|                        |")
print("|                        |")
print("|                        |")
print("|________ver1.0.0________|")
